name: fastcampusmarket
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  # --- Flutter 기본 및 UI 관련 ---
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  smooth_page_indicator: ^1.2.1
  flutter_image_compress: ^2.4.0

  # --- 상태 관리 및 라우팅 ---
  flutter_hooks: ^0.21.2
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  go_router: ^15.1.1

  # --- Firebase 관련 ---
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0

  # --- 이미지 및 기타 유틸리티 ---
  image_picker: ^1.1.2
  intl: ^0.20.2

  # --- 코드 생성/직렬화 어노테이션 ---
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  timeago: ^3.2.2
  uuid: ^4.5.1



dev_dependencies:
  # --- 테스트 및 린트 ---
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # --- 코드 생성 도구 ---
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/logo/google/
    - assets/images/logo/google/light/
    - assets/images/logo/google/dark/
    - assets/images/logo/indischool/

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700