// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4LmLHkXp6IUgF0d63Ge7QWwoG2RSif8',
    appId: '1:355140441526:android:4f8b087c5ccc45cbbe5d17',
    messagingSenderId: '355140441526',
    projectId: 'fastcampusmarket-98acf',
    storageBucket: 'fastcampusmarket-98acf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSeELPEK53euVpDer9PNpzYRZo6rVQXOw',
    appId: '1:355140441526:ios:81791c503c17c5d6be5d17',
    messagingSenderId: '355140441526',
    projectId: 'fastcampusmarket-98acf',
    storageBucket: 'fastcampusmarket-98acf.firebasestorage.app',
    iosClientId: '355140441526-7vg7ci90d47b3kdpnpnsvkei2h56d7lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastcampusmarket',
  );

}